export * as authController from "./auth.controller"
export * as doctorController from "./doctor.controller"
export * as patientController from "./patient/patient.controller"
export * as paymentController from "./patient/payment.controller"
export * as reviewController from "./patient/review.controller";
export * as appointmentController from "./patient/appointment.controller";
export * as doctorPatient from './DoctorPatients'
export * as adminController from './admin.controller'
export * as paymentDoctorController from './doctorPayment'
export * as appointmentDoctorController from './doctorApppointments.controller'
export * as medicalHistoryController from './patient/medicalHistory.controller'